import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Banner from "@/components/Banner/Banner";
import Navbar from "@/components/nav/Navbar";
import CardSection from "@/components/Card/CardSection";

export default function Home() {
  const disneVideos = [
    {
      imgUrl: "/static/clifford.webp",
    },
    {
      imgUrl: "/static/clifford.webp",
    },
    {
      imgUrl: "/static/clifford.webp",
    },
    {
      imgUrl: "/static/clifford.webp",
    },
  ];

  return (
    <>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar username="test@test.com" />
        <Banner
          title="Clifford The Red Dog"
          subtitle="The very Cute Dog"
          imgUrl="/static/clifford.webp"
        />

        <div className={styles.sectionWrapper}>
          <CardSection title="Disney" videos={disneVideos} size="large" />
          <CardSection title="Productive" videos={disneVideos} size="medium" />
        </div>
      </main>
    </>
  );
}
