import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Banner from "@/components/Banner/Banner";
import Navbar from "@/components/nav/Navbar";
import CardSection from "@/components/Card/CardSection";
import { getPopularVideos, getVideos } from "@/lib/videos";

// This gets called on every request
export async function getServerSideProps() {
  const disneVideos = await getVideos("disney trailer");
  const travelVideos = await getVideos("travel");
  const productivityVideos = await getVideos("productivity");
  const popularVideos = await getPopularVideos();

  // Pass data to the Home via props
  return {
    props: { disneVideos, travelVideos, productivityVideos, popularVideos },
  };
}

export default function Home({
  disneVideos,
  travelVideos,
  productivityVideos,
  popularVideos,
}) {
  return (
    <>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar username="test@test.com" />
        <Banner
          title="Clifford The Red Dog"
          subtitle="The very Cute Dog"
          imgUrl="/static/clifford.webp"
        />

        <div className={styles.sectionWrapper}>
          <CardSection title="Disney" videos={disneVideos} size="large" />
          <CardSection title="Travel" videos={travelVideos} size="small" />
          <CardSection
            title="Productivity"
            videos={productivityVideos}
            size="medium"
          />
          <CardSection title="Popular" videos={popularVideos} size="small" />
        </div>
      </main>
    </>
  );
}
